name: Edgar Download and Push

on: push # Schedule the workflow to run daily (adjust the timing as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install tqdm requests

      - name: Run Python script
        run: python main.py  # Replace with the path to your Python script
